#conceito=str(input("digite o conceito aqdiquirido de A a E:"))
#match conceito:
#    case "a": print("otimo")
#    case "b": print("qualificado")
 #   case "c": print("aprimore")
#    case "d":print("recuperação")
#    case "e": print("reprovado")
  #  case "E": print("reprovado")
   # case "D": print("recuperação")
  #  case "C": print("aprimore")
 #   case "B": print("qualificado")
  #  case "A": print("otimo")
 #   case other: print(" conceito invalido")
#exercicio 2
mes= str(input("bem vindo ao estacionador do ano qual mes que nos estamos? "))
match mes :
    case "Janeiro":  print("verão")
    case "Fevereiro":  print("verão")
    case "Dezembro": print("verão")
    case"Março": print("outono")
    case "Abril":print("outono")
    case "Maio": print("outono")
    case "Junho":print("inverno")
    case "Julho":print("inverno")
    case "Agosto":print("inverno")
    case "Setembro":print("primavera")
    case "Outubro":print("primavera")
    case "novembro":print("primavera")
    case other:print("mes invalido. coloque letra maiuscula no inicio do mes")
    